/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWatchlistRouteImport } from './routes/_authenticated/app.watchlist'
import { Route as AuthenticatedAppVideosRouteImport } from './routes/_authenticated/app.videos'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppSubscriptionRouteImport } from './routes/_authenticated/app.subscription'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppPdfsRouteImport } from './routes/_authenticated/app.pdfs'
import { Route as AuthenticatedAppLibraryRouteImport } from './routes/_authenticated/app.library'
import { Route as AuthenticatedAppFavoritesRouteImport } from './routes/_authenticated/app.favorites'
import { Route as AuthenticatedAppDownloadsRouteImport } from './routes/_authenticated/app.downloads'
import { Route as AuthenticatedAppDiscoverRouteImport } from './routes/_authenticated/app.discover'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppAudiosRouteImport } from './routes/_authenticated/app.audios'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAppContentSlugRouteImport } from './routes/_authenticated/app.content.$slug'
import { Route as AuthenticatedAppAdminUploadsRouteImport } from './routes/_authenticated/app.admin.uploads'
import { Route as AuthenticatedAppAdminMembersRouteImport } from './routes/_authenticated/app.admin.members'
import { Route as AuthenticatedAppAdminMediaRouteImport } from './routes/_authenticated/app.admin.media'
import { Route as AuthenticatedAppAdminLogsRouteImport } from './routes/_authenticated/app.admin.logs'
import { Route as AuthenticatedAppAdminIntelligenceRouteImport } from './routes/_authenticated/app.admin.intelligence'
import { Route as AuthenticatedAppAdminCommentsRouteImport } from './routes/_authenticated/app.admin.comments'
import { Route as AuthenticatedAppAdminCollectionsRouteImport } from './routes/_authenticated/app.admin.collections'
import { Route as AuthenticatedAppAdminCategoriesRouteImport } from './routes/_authenticated/app.admin.categories'
import { Route as AuthenticatedAppAdminBillingRouteImport } from './routes/_authenticated/app.admin.billing'
import { Route as AuthenticatedAppAdminAnnouncementsRouteImport } from './routes/_authenticated/app.admin.announcements'
import { Route as AuthenticatedAppAdminContentIndexRouteImport } from './routes/_authenticated/app.admin.content.index'
import { Route as AuthenticatedAppAdminContentNewRouteImport } from './routes/_authenticated/app.admin.content.new'
import { Route as AuthenticatedAppAdminContentIdRouteImport } from './routes/_authenticated/app.admin.content.$id'
import { Route as AuthenticatedAppAdminContentEditRouteImport } from './routes/_authenticated/app.admin.content.edit.'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExploreRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWatchlistRoute =
  AuthenticatedAppWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVideosRoute = AuthenticatedAppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSubscriptionRoute =
  AuthenticatedAppSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPdfsRoute = AuthenticatedAppPdfsRouteImport.update({
  id: '/pdfs',
  path: '/pdfs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLibraryRoute = AuthenticatedAppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFavoritesRoute =
  AuthenticatedAppFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDownloadsRoute =
  AuthenticatedAppDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDiscoverRoute =
  AuthenticatedAppDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAudiosRoute = AuthenticatedAppAudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppContentSlugRoute =
  AuthenticatedAppContentSlugRouteImport.update({
    id: '/content/$slug',
    path: '/content/$slug',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminUploadsRoute =
  AuthenticatedAppAdminUploadsRouteImport.update({
    id: '/uploads',
    path: '/uploads',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminMembersRoute =
  AuthenticatedAppAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminMediaRoute =
  AuthenticatedAppAdminMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminLogsRoute =
  AuthenticatedAppAdminLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminIntelligenceRoute =
  AuthenticatedAppAdminIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCommentsRoute =
  AuthenticatedAppAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCollectionsRoute =
  AuthenticatedAppAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCategoriesRoute =
  AuthenticatedAppAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminBillingRoute =
  AuthenticatedAppAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAnnouncementsRoute =
  AuthenticatedAppAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContentIndexRoute =
  AuthenticatedAppAdminContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContentNewRoute =
  AuthenticatedAppAdminContentNewRouteImport.update({
    id: '/content/new',
    path: '/content/new',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContentIdRoute =
  AuthenticatedAppAdminContentIdRouteImport.update({
    id: '/content/$id',
    path: '/content/$id',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminContentEditRoute =
  AuthenticatedAppAdminContentEditRouteImport.update({
    id: '/content/edit/',
    path: '/content/edit/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/audios': typeof AuthenticatedAppAudiosRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/downloads': typeof AuthenticatedAppDownloadsRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/pdfs': typeof AuthenticatedAppPdfsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/announcements': typeof AuthenticatedAppAdminAnnouncementsRoute
  '/app/admin/billing': typeof AuthenticatedAppAdminBillingRoute
  '/app/admin/categories': typeof AuthenticatedAppAdminCategoriesRoute
  '/app/admin/collections': typeof AuthenticatedAppAdminCollectionsRoute
  '/app/admin/comments': typeof AuthenticatedAppAdminCommentsRoute
  '/app/admin/intelligence': typeof AuthenticatedAppAdminIntelligenceRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/media': typeof AuthenticatedAppAdminMediaRoute
  '/app/admin/members': typeof AuthenticatedAppAdminMembersRoute
  '/app/admin/uploads': typeof AuthenticatedAppAdminUploadsRoute
  '/app/content/$slug': typeof AuthenticatedAppContentSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/content/$id': typeof AuthenticatedAppAdminContentIdRoute
  '/app/admin/content/new': typeof AuthenticatedAppAdminContentNewRoute
  '/app/admin/content/': typeof AuthenticatedAppAdminContentIndexRoute
  '/app/admin/content/edit/': typeof AuthenticatedAppAdminContentEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/audios': typeof AuthenticatedAppAudiosRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/app/downloads': typeof AuthenticatedAppDownloadsRoute
  '/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/app/library': typeof AuthenticatedAppLibraryRoute
  '/app/pdfs': typeof AuthenticatedAppPdfsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/announcements': typeof AuthenticatedAppAdminAnnouncementsRoute
  '/app/admin/billing': typeof AuthenticatedAppAdminBillingRoute
  '/app/admin/categories': typeof AuthenticatedAppAdminCategoriesRoute
  '/app/admin/collections': typeof AuthenticatedAppAdminCollectionsRoute
  '/app/admin/comments': typeof AuthenticatedAppAdminCommentsRoute
  '/app/admin/intelligence': typeof AuthenticatedAppAdminIntelligenceRoute
  '/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/app/admin/media': typeof AuthenticatedAppAdminMediaRoute
  '/app/admin/members': typeof AuthenticatedAppAdminMembersRoute
  '/app/admin/uploads': typeof AuthenticatedAppAdminUploadsRoute
  '/app/content/$slug': typeof AuthenticatedAppContentSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/admin/content/$id': typeof AuthenticatedAppAdminContentIdRoute
  '/app/admin/content/new': typeof AuthenticatedAppAdminContentNewRoute
  '/app/admin/content': typeof AuthenticatedAppAdminContentIndexRoute
  '/app/admin/content/edit': typeof AuthenticatedAppAdminContentEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/audios': typeof AuthenticatedAppAudiosRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/discover': typeof AuthenticatedAppDiscoverRoute
  '/_authenticated/app/downloads': typeof AuthenticatedAppDownloadsRoute
  '/_authenticated/app/favorites': typeof AuthenticatedAppFavoritesRoute
  '/_authenticated/app/library': typeof AuthenticatedAppLibraryRoute
  '/_authenticated/app/pdfs': typeof AuthenticatedAppPdfsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/subscription': typeof AuthenticatedAppSubscriptionRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/videos': typeof AuthenticatedAppVideosRoute
  '/_authenticated/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/announcements': typeof AuthenticatedAppAdminAnnouncementsRoute
  '/_authenticated/app/admin/billing': typeof AuthenticatedAppAdminBillingRoute
  '/_authenticated/app/admin/categories': typeof AuthenticatedAppAdminCategoriesRoute
  '/_authenticated/app/admin/collections': typeof AuthenticatedAppAdminCollectionsRoute
  '/_authenticated/app/admin/comments': typeof AuthenticatedAppAdminCommentsRoute
  '/_authenticated/app/admin/intelligence': typeof AuthenticatedAppAdminIntelligenceRoute
  '/_authenticated/app/admin/logs': typeof AuthenticatedAppAdminLogsRoute
  '/_authenticated/app/admin/media': typeof AuthenticatedAppAdminMediaRoute
  '/_authenticated/app/admin/members': typeof AuthenticatedAppAdminMembersRoute
  '/_authenticated/app/admin/uploads': typeof AuthenticatedAppAdminUploadsRoute
  '/_authenticated/app/content/$slug': typeof AuthenticatedAppContentSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/admin/content/$id': typeof AuthenticatedAppAdminContentIdRoute
  '/_authenticated/app/admin/content/new': typeof AuthenticatedAppAdminContentNewRoute
  '/_authenticated/app/admin/content/': typeof AuthenticatedAppAdminContentIndexRoute
  '/_authenticated/app/admin/content/edit/': typeof AuthenticatedAppAdminContentEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/faq'
    | '/login'
    | '/manifesto'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/checkout/return'
    | '/explore/$slug'
    | '/app/admin'
    | '/app/agenda'
    | '/app/audios'
    | '/app/community'
    | '/app/discover'
    | '/app/downloads'
    | '/app/favorites'
    | '/app/library'
    | '/app/pdfs'
    | '/app/settings'
    | '/app/subscription'
    | '/app/support'
    | '/app/videos'
    | '/app/watchlist'
    | '/app/'
    | '/app/admin/announcements'
    | '/app/admin/billing'
    | '/app/admin/categories'
    | '/app/admin/collections'
    | '/app/admin/comments'
    | '/app/admin/intelligence'
    | '/app/admin/logs'
    | '/app/admin/media'
    | '/app/admin/members'
    | '/app/admin/uploads'
    | '/app/content/$slug'
    | '/api/public/payments/webhook'
    | '/app/admin/'
    | '/app/admin/content/$id'
    | '/app/admin/content/new'
    | '/app/admin/content/'
    | '/app/admin/content/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/faq'
    | '/login'
    | '/manifesto'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signup'
    | '/checkout/return'
    | '/explore/$slug'
    | '/app/agenda'
    | '/app/audios'
    | '/app/community'
    | '/app/discover'
    | '/app/downloads'
    | '/app/favorites'
    | '/app/library'
    | '/app/pdfs'
    | '/app/settings'
    | '/app/subscription'
    | '/app/support'
    | '/app/videos'
    | '/app/watchlist'
    | '/app'
    | '/app/admin/announcements'
    | '/app/admin/billing'
    | '/app/admin/categories'
    | '/app/admin/collections'
    | '/app/admin/comments'
    | '/app/admin/intelligence'
    | '/app/admin/logs'
    | '/app/admin/media'
    | '/app/admin/members'
    | '/app/admin/uploads'
    | '/app/content/$slug'
    | '/api/public/payments/webhook'
    | '/app/admin'
    | '/app/admin/content/$id'
    | '/app/admin/content/new'
    | '/app/admin/content'
    | '/app/admin/content/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/explore'
    | '/faq'
    | '/login'
    | '/manifesto'
    | '/pricing'
    | '/research'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/checkout/return'
    | '/explore/$slug'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/audios'
    | '/_authenticated/app/community'
    | '/_authenticated/app/discover'
    | '/_authenticated/app/downloads'
    | '/_authenticated/app/favorites'
    | '/_authenticated/app/library'
    | '/_authenticated/app/pdfs'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/subscription'
    | '/_authenticated/app/support'
    | '/_authenticated/app/videos'
    | '/_authenticated/app/watchlist'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/announcements'
    | '/_authenticated/app/admin/billing'
    | '/_authenticated/app/admin/categories'
    | '/_authenticated/app/admin/collections'
    | '/_authenticated/app/admin/comments'
    | '/_authenticated/app/admin/intelligence'
    | '/_authenticated/app/admin/logs'
    | '/_authenticated/app/admin/media'
    | '/_authenticated/app/admin/members'
    | '/_authenticated/app/admin/uploads'
    | '/_authenticated/app/content/$slug'
    | '/api/public/payments/webhook'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/admin/content/$id'
    | '/_authenticated/app/admin/content/new'
    | '/_authenticated/app/admin/content/'
    | '/_authenticated/app/admin/content/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  ManifestoRoute: typeof ManifestoRoute
  PricingRoute: typeof PricingRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/watchlist': {
      id: '/_authenticated/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AuthenticatedAppWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/videos': {
      id: '/_authenticated/app/videos'
      path: '/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AuthenticatedAppVideosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/subscription': {
      id: '/_authenticated/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AuthenticatedAppSubscriptionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pdfs': {
      id: '/_authenticated/app/pdfs'
      path: '/pdfs'
      fullPath: '/app/pdfs'
      preLoaderRoute: typeof AuthenticatedAppPdfsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/library': {
      id: '/_authenticated/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AuthenticatedAppLibraryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/favorites': {
      id: '/_authenticated/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AuthenticatedAppFavoritesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/downloads': {
      id: '/_authenticated/app/downloads'
      path: '/downloads'
      fullPath: '/app/downloads'
      preLoaderRoute: typeof AuthenticatedAppDownloadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/discover': {
      id: '/_authenticated/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AuthenticatedAppDiscoverRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audios': {
      id: '/_authenticated/app/audios'
      path: '/audios'
      fullPath: '/app/audios'
      preLoaderRoute: typeof AuthenticatedAppAudiosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/content/$slug': {
      id: '/_authenticated/app/content/$slug'
      path: '/content/$slug'
      fullPath: '/app/content/$slug'
      preLoaderRoute: typeof AuthenticatedAppContentSlugRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/uploads': {
      id: '/_authenticated/app/admin/uploads'
      path: '/uploads'
      fullPath: '/app/admin/uploads'
      preLoaderRoute: typeof AuthenticatedAppAdminUploadsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/members': {
      id: '/_authenticated/app/admin/members'
      path: '/members'
      fullPath: '/app/admin/members'
      preLoaderRoute: typeof AuthenticatedAppAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/media': {
      id: '/_authenticated/app/admin/media'
      path: '/media'
      fullPath: '/app/admin/media'
      preLoaderRoute: typeof AuthenticatedAppAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/logs': {
      id: '/_authenticated/app/admin/logs'
      path: '/logs'
      fullPath: '/app/admin/logs'
      preLoaderRoute: typeof AuthenticatedAppAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/intelligence': {
      id: '/_authenticated/app/admin/intelligence'
      path: '/intelligence'
      fullPath: '/app/admin/intelligence'
      preLoaderRoute: typeof AuthenticatedAppAdminIntelligenceRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/comments': {
      id: '/_authenticated/app/admin/comments'
      path: '/comments'
      fullPath: '/app/admin/comments'
      preLoaderRoute: typeof AuthenticatedAppAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/collections': {
      id: '/_authenticated/app/admin/collections'
      path: '/collections'
      fullPath: '/app/admin/collections'
      preLoaderRoute: typeof AuthenticatedAppAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/categories': {
      id: '/_authenticated/app/admin/categories'
      path: '/categories'
      fullPath: '/app/admin/categories'
      preLoaderRoute: typeof AuthenticatedAppAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/billing': {
      id: '/_authenticated/app/admin/billing'
      path: '/billing'
      fullPath: '/app/admin/billing'
      preLoaderRoute: typeof AuthenticatedAppAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/announcements': {
      id: '/_authenticated/app/admin/announcements'
      path: '/announcements'
      fullPath: '/app/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAppAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/content/': {
      id: '/_authenticated/app/admin/content/'
      path: '/content'
      fullPath: '/app/admin/content/'
      preLoaderRoute: typeof AuthenticatedAppAdminContentIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/content/new': {
      id: '/_authenticated/app/admin/content/new'
      path: '/content/new'
      fullPath: '/app/admin/content/new'
      preLoaderRoute: typeof AuthenticatedAppAdminContentNewRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/content/$id': {
      id: '/_authenticated/app/admin/content/$id'
      path: '/content/$id'
      fullPath: '/app/admin/content/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminContentIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/content/edit/': {
      id: '/_authenticated/app/admin/content/edit/'
      path: '/content/edit'
      fullPath: '/app/admin/content/edit/'
      preLoaderRoute: typeof AuthenticatedAppAdminContentEditRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminAnnouncementsRoute: typeof AuthenticatedAppAdminAnnouncementsRoute
  AuthenticatedAppAdminBillingRoute: typeof AuthenticatedAppAdminBillingRoute
  AuthenticatedAppAdminCategoriesRoute: typeof AuthenticatedAppAdminCategoriesRoute
  AuthenticatedAppAdminCollectionsRoute: typeof AuthenticatedAppAdminCollectionsRoute
  AuthenticatedAppAdminCommentsRoute: typeof AuthenticatedAppAdminCommentsRoute
  AuthenticatedAppAdminIntelligenceRoute: typeof AuthenticatedAppAdminIntelligenceRoute
  AuthenticatedAppAdminLogsRoute: typeof AuthenticatedAppAdminLogsRoute
  AuthenticatedAppAdminMediaRoute: typeof AuthenticatedAppAdminMediaRoute
  AuthenticatedAppAdminMembersRoute: typeof AuthenticatedAppAdminMembersRoute
  AuthenticatedAppAdminUploadsRoute: typeof AuthenticatedAppAdminUploadsRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminContentIdRoute: typeof AuthenticatedAppAdminContentIdRoute
  AuthenticatedAppAdminContentNewRoute: typeof AuthenticatedAppAdminContentNewRoute
  AuthenticatedAppAdminContentIndexRoute: typeof AuthenticatedAppAdminContentIndexRoute
  AuthenticatedAppAdminContentEditRoute: typeof AuthenticatedAppAdminContentEditRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminAnnouncementsRoute:
    AuthenticatedAppAdminAnnouncementsRoute,
  AuthenticatedAppAdminBillingRoute: AuthenticatedAppAdminBillingRoute,
  AuthenticatedAppAdminCategoriesRoute: AuthenticatedAppAdminCategoriesRoute,
  AuthenticatedAppAdminCollectionsRoute: AuthenticatedAppAdminCollectionsRoute,
  AuthenticatedAppAdminCommentsRoute: AuthenticatedAppAdminCommentsRoute,
  AuthenticatedAppAdminIntelligenceRoute:
    AuthenticatedAppAdminIntelligenceRoute,
  AuthenticatedAppAdminLogsRoute: AuthenticatedAppAdminLogsRoute,
  AuthenticatedAppAdminMediaRoute: AuthenticatedAppAdminMediaRoute,
  AuthenticatedAppAdminMembersRoute: AuthenticatedAppAdminMembersRoute,
  AuthenticatedAppAdminUploadsRoute: AuthenticatedAppAdminUploadsRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminContentIdRoute: AuthenticatedAppAdminContentIdRoute,
  AuthenticatedAppAdminContentNewRoute: AuthenticatedAppAdminContentNewRoute,
  AuthenticatedAppAdminContentIndexRoute:
    AuthenticatedAppAdminContentIndexRoute,
  AuthenticatedAppAdminContentEditRoute: AuthenticatedAppAdminContentEditRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAudiosRoute: typeof AuthenticatedAppAudiosRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppDiscoverRoute: typeof AuthenticatedAppDiscoverRoute
  AuthenticatedAppDownloadsRoute: typeof AuthenticatedAppDownloadsRoute
  AuthenticatedAppFavoritesRoute: typeof AuthenticatedAppFavoritesRoute
  AuthenticatedAppLibraryRoute: typeof AuthenticatedAppLibraryRoute
  AuthenticatedAppPdfsRoute: typeof AuthenticatedAppPdfsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSubscriptionRoute: typeof AuthenticatedAppSubscriptionRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppVideosRoute: typeof AuthenticatedAppVideosRoute
  AuthenticatedAppWatchlistRoute: typeof AuthenticatedAppWatchlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppContentSlugRoute: typeof AuthenticatedAppContentSlugRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAudiosRoute: AuthenticatedAppAudiosRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppDiscoverRoute: AuthenticatedAppDiscoverRoute,
  AuthenticatedAppDownloadsRoute: AuthenticatedAppDownloadsRoute,
  AuthenticatedAppFavoritesRoute: AuthenticatedAppFavoritesRoute,
  AuthenticatedAppLibraryRoute: AuthenticatedAppLibraryRoute,
  AuthenticatedAppPdfsRoute: AuthenticatedAppPdfsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSubscriptionRoute: AuthenticatedAppSubscriptionRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppVideosRoute: AuthenticatedAppVideosRoute,
  AuthenticatedAppWatchlistRoute: AuthenticatedAppWatchlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppContentSlugRoute: AuthenticatedAppContentSlugRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ExploreRouteChildren {
  ExploreSlugRoute: typeof ExploreSlugRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreSlugRoute: ExploreSlugRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  ManifestoRoute: ManifestoRoute,
  PricingRoute: PricingRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
